workflows:
  android-native:
    name: Android Native Build

    scripts:
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
